#!/bin/bash
# Created by Roel Van de Paar, Percona LLC

# For a given trial, this script quickly produces a tarball containing: 
# the core file generated by that trial, the mysqld used by that trial, and the ldd dependency files needed by that mysqld
# This can be used to quickly get a tarball which is ready to be added to a bug report for analysis by developers

if [ "" == "$1" ]; then
  echo "This script creates a tarball with the core file, mysqld binary and ldd dep. files. It expects one parameter: the trial number to process"
  echo "Note; this script relies on the ldd_files.sh script to be present in the same directory as this script"
  exit 1
else
  TRIAL=$1
  SCRIPT_PWD=$(cd `dirname $0` && pwd)
  if [ ! -r ./cmd${TRIAL} ]; then
    echo "Something is wrong: ./cmd${TRIAL} does not exist or cannot be read?"
    echo "Execute the 'startup.sh' script first for this trial."
    exit 1
  elif [ ! -d ./vardir1_${TRIAL} ]; then
    if [ -r ./vardir1_${TRIAL}.tar.gz ]; then
      tar -xf ./vardir1_${TRIAL}.tar.gz
      if [ ! -d ./vardir1_${TRIAL} ]; then
        echo "Something is wrong: ./vardir1_${TRIAL} does not exist?"
        echo "However, ./vardir1_${TRIAL}.tar.gz exists, and we tried extracting it, but it seemed to have failed?"
        exit 1
      fi
    else
      echo "Something is wrong: ./vardir1_${TRIAL} nor ./vardir1_${TRIAL}.tar.gz exist?"
      exit 1
    fi
  fi
  if [ ! -r ./trial${TRIAL}.log ]; then
    echo "Something is wrong: ./trial_${TRIAL}.log does not exist?"
    exit 1
  elif [ ! -r ./vardir1_${TRIAL}/master-data/*core* ]; then
    echo "Something is wrong: there is no (script readable) [vg]core in ./vardir1_${TRIAL}/master-data/ ? [Test 1]"
    exit 1
  fi
fi

WORKD_PWD=$PWD
BASE=`grep -m1 'basedir=' trial${TRIAL}.log | sed 's|^.*basedir=/|/|;s| .*$||'`
echo "BASE directory: ${BASE}"

cd vardir1_${TRIAL}/master-data
CORE_FILE=`ls -1 *core* 2>&1 | head -n1 | grep -v "No such file"`
CORE=${WORKD_PWD}/vardir1_${TRIAL}/master-data/$CORE_FILE

if [ ! -f $CORE -o "" == "${CORE}" ]; then
  echo "Something is wrong: there is no (script readable) core available at $CORE ? [Test 2]"
  exit 1
else
  echo "Core found at: $CORE"
fi

if [ -r ${BASE}/bin/mysqld ]; then
  BIN=${BASE}/bin/mysqld
else
  # Check if this is a debug build by checking if debug string is present in dirname
  if [[ ${BASE} = *debug* ]]; then
    if [ -r ${BASE}/bin/mysqld-debug ]; then
      BIN=${BASE}/bin/mysqld-debug
    else
      echo "Something is wrong: there is no (script readable) mysqld binary at ${BASE}/bin/mysqld[-debug] ?"
      exit 1
    fi
  else
    echo "Something is wrong: there is no (script readable) mysqld binary at ${BASE}/bin/mysqld ?"
    exit 1
  fi
fi

CP_PATH=${WORKD_PWD}/CORE_${TRIAL}

# Cleanup existing CORE_<trial> directory
if [ -d ${CP_PATH} ]; then 
  cd ${CP_PATH}
  if [ "" != "$(pwd | grep 'CORE_')" ]; then     # Safety mechanism to ensure ${CP_PATH} contains "CORE_" and that the directory exists
    cd ..
    rm -Rf ${CP_PATH}
  else
    echo "Assert: this should never happen [01]. Maybe privileges related? Please improve script."
    exit 1
  fi
fi

# Create new/fresh CORE_<trial> directory
mkdir ${CP_PATH}
cd ${CP_PATH}
if [ "" == "$(pwd | grep 'CORE_')" ]; then
  echo "Something is wrong: tried to create '$CP_PATH' and changedir (cd) to it, but that failed (out of disk space or privileges related?)"
  exit 1
fi

# Copy mysqld binary in
cp $BIN .
if [ "" == "$(ls | grep mysqld)" ]; then
  echo "Something is wrong: tried to copy mysqld ($BIN) to this path ($CP_PATH), but that failed (out of disk space?)"
  exit 1
fi

# Copy core file in
cp $CORE .
if [ "" == "$(ls | grep core)" ]; then
  echo "Something is wrong: tried to copy the core file ($CORE) to this path ($CP_PATH), but that failed (out of disk space?)"
  exit 1
fi

# Get ldd dependency files using external script
${SCRIPT_PWD}/ldd_files.sh

TIMEF=`date +%d%m%y-%H%M`
TAR=core_${TRIAL}_${TIMEF}.tar.gz
tar -zhcf $TAR *
mv $TAR ${WORKD_PWD}
cd ${WORKD_PWD}

if [ ! -f $TAR ]; then
  echo "Something is wrong: the tar file $TAR should exist, but it doesn't (out of disk space?)"
  exit 1
fi

# rm -Rf ${CP_PATH}

echo "Core file, mysqld binary and ldd dependency files successfully tarred up together as $TAR"
